import test from 'node:test';import assert from 'node:assert/strict';
import {loadToolModule} from '../src/components/load-tool-module.js';
test('transient entry fetch retries once with a distinct module key',async()=>{const calls=[];const module={ready:true};const result=await loadToolModule('https://fixture.test/tool.js?v=1',{pause:async()=>{},importer:async url=>{calls.push(url);if(calls.length===1)throw TypeError('fetch failure');return module;}});assert.equal(result,module);assert.equal(calls[0],'https://fixture.test/tool.js?v=1');assert.ok(new URL(calls[1]).searchParams.has('oxImportRetry'));assert.notEqual(calls[0],calls[1]);});
test('navigation away cancels retry and persistent errors remain bounded',async()=>{let active=true,calls=0;await assert.rejects(loadToolModule('https://fixture.test/tool.js',{current:()=>active,pause:async()=>{active=false;},importer:async()=>{calls++;throw TypeError('fetch failure');}}));assert.equal(calls,1);calls=0;await assert.rejects(loadToolModule('https://fixture.test/tool.js',{pause:async()=>{},importer:async()=>{calls++;throw TypeError('fetch failure');}}));assert.equal(calls,2);});

test('late successful import initializes once and never starts a retry timer',async()=>{let release,calls=0,pauses=0;const deferred=new Promise(r=>release=r),module={ready:true};const pending=loadToolModule('https://fixture.test/tool.js',{pause:async()=>{pauses++;},importer:async()=>{calls++;return deferred;}});release(module);assert.equal(await pending,module);assert.equal(calls,1);assert.equal(pauses,0);});
test('manual retry escapes rejected module keys with a finite pair of requests',async()=>{const calls=[];const options={pause:async()=>{},importer:async url=>{calls.push(url);throw TypeError('persistent fetch failure');}};for(let n=0;n<2;n++)await assert.rejects(loadToolModule('https://fixture.test/manual-only.js?v=1',options));assert.equal(new Set(calls).size,4);assert.equal(calls.length,4);});

test('module evaluation errors are not replayed and cannot duplicate top-level side effects',async()=>{let calls=0;await assert.rejects(loadToolModule('https://fixture.test/evaluation-only.js',{pause:async()=>{},importer:async()=>{calls++;throw TypeError('Cannot read properties of undefined');}}));assert.equal(calls,1);});
