import { buildFlow, STATES, signed, compact, dateLabel } from './flow-model.js';
import { buildRotation, heatmapRows, derivativeRows, orderFlow, ROTATION_STATES, TOOL_PERIODS } from './tools-model.js';
import { createFlowChart } from './flow-chart.js';
import { createToolChart } from './tools-charts.js';
import { refreshFlow } from './flow-source.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={close:'<path d="m6 6 12 12M18 6 6 18"/>',back:'<path d="m10 5-7 7 7 7M3 12h18"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',reset:'<path d="M3 4v6h6M4 10a8 8 0 1 1 1 8"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 4v16M16 4v16"/>',plus:'<path d="M5 12h14M12 5v14"/>',minus:'<path d="M5 12h14"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`;
const snapshotURL=new URL('../../../../previews/data/crypto-flow-snapshot.json',import.meta.url);
const marketURL=new URL('../../../../previews/data/crypto-tools-snapshot.json',import.meta.url);
const liquidationURL=new URL('../../../../previews/data/crypto-liquidations-snapshot.json',import.meta.url);
const cssURL=new URL('./flow.css',import.meta.url);
const numPrice=v=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:v<1?6:2}):'—';
const pct=v=>Number.isFinite(v)?signed(v,2)+'%':'—';
const pp=v=>Number.isFinite(v)?signed(v,2)+'pp':'—';
const color=v=>v>=0?'positive':'negative';
const time=t=>new Date(t).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false});
const TABS=[['overview','總覽'],['heatmap','熱力圖'],['rotation','板塊輪動'],['flow','主動買賣'],['derivatives','合約'],['liquidations','爆倉'],['zones','清算'],['order','訂單流']];
export function mountCryptoFlow(host,{onExit=()=>{},snapshot=null,marketSnapshot=null,liquidationSnapshot=null,initialTab='rotation'}={}) {
 const shadow=host.shadowRoot||host.attachShadow({mode:'open'}),life=new AbortController();
 const state={tab:TABS.some(([id])=>id===initialTab)?initialTab:'rotation',period:'1h',heatPeriod:'24h',selected:'',filter:'',sector:'',search:'',frame:7,equal:true,trails:false,table:false,weight:'volume',grouped:false,focus:false,orderMode:'footprint',symbol:'BTCUSDT',step:10,count:3,liqPeriod:24,liqSymbol:'all',sort:'relative',watch:false};
 let market=marketSnapshot,flowSnapshot=snapshot,liq=liquidationSnapshot,rotation=null,plot=null,otherPlot=null,replay=null,request=null,ws=null,ping=null;
 const pressureSnapshots=new Map();
 const pressureSnapshot=()=>pressureSnapshots.get(state.period)||flowSnapshot;
 const watched=new Set();try{for(const s of JSON.parse(localStorage.getItem('ox-crypto-sector-watch')||'[]'))watched.add(s);}catch{}
 shadow.innerHTML=`<link rel="stylesheet" href="${cssURL.href}"><main class="cfx"><header class="cfx-top"><button class="cfx-icon cfx-back" data-action="exit" aria-label="返回指標">${icon('back')}</button><span class="cfx-brand">OX<span>CRYPTO</span></span><span class="cfx-source-badge">BITGET · USDT 永續</span><div class="cfx-top-actions"><button class="cfx-icon" data-action="help" aria-label="資料與計算說明">${icon('info')}</button><button class="cfx-exit" data-action="fullscreen">${icon('expand')}<span data-slot="exit-label">全螢幕</span></button></div></header><nav class="cfx-tabs" aria-label="Crypto 工具">${TABS.map(([id,label])=>`<button data-tab="${id}" aria-pressed="${id===state.tab}">${label}</button>`).join('')}</nav><section class="cfx-content" aria-label="工具內容"></section><footer class="cfx-status" role="status"><span data-slot="source">讀取來源資料…</span><span data-slot="period"></span></footer><div class="cfx-notice" role="status" hidden></div><dialog class="cfx-dialog" aria-label="資料與計算說明"><div class="cfx-dialog-head"><span>資料與計算</span><button class="cfx-close" data-action="close-help" aria-label="關閉說明">${icon('close')}</button></div><div data-slot="help"></div></dialog><dialog class="cfx-asset-dialog" aria-label="標的詳情"><div class="cfx-dialog-head"><span data-slot="asset-title"></span><button class="cfx-close" data-action="close-asset" aria-label="關閉標的詳情">${icon('close')}</button></div><div data-slot="asset"></div></dialog></main>`;
 const q=s=>shadow.querySelector(s),qa=s=>[...shadow.querySelectorAll(s)];
 const notice=text=>{q('.cfx-notice').textContent=text;q('.cfx-notice').hidden=!text;};
 function cleanup(){request?.abort();plot?.destroy();otherPlot?.destroy();plot=otherPlot=null;stopReplay();if(ws){ws.close();ws=null;}clearInterval(ping);}
 function stopReplay(){clearInterval(replay);replay=null;const b=q('[data-action="play"]');if(b){b.innerHTML=icon('play');b.setAttribute('aria-label','播放輪動回放');}}
 function periodButtons(p,heat=false){return `<div class="cfx-period">${Object.keys(TOOL_PERIODS).filter(t=>heat||t!=='24h').map(t=>`<button data-period="${t}" aria-pressed="${p===t}">${t.toUpperCase()}</button>`).join('')}</div>`;}
 const search=()=>`<label class="cfx-search">${icon('search')}<input aria-label="搜尋板塊或幣種" placeholder="搜尋" value="${escape(state.search)}"></label>`;
 const empty=text=>`<div class="cfx-empty">${text}</div>`;
 function status(text,stamp){q('[data-slot="source"]').textContent=text;q('[data-slot="period"]').textContent=stamp?dateLabel(stamp)+' UTC+8':'';}
 function openAsset(symbol){const rows=heatmapRows(market,state.heatPeriod),r=rows.find(x=>x.symbol===symbol),d=derivativeRows(market).find(x=>x.symbol===symbol);q('[data-slot="asset-title"]').textContent=symbol.replace(/USDT$/,'');q('[data-slot="asset"]').innerHTML=`<div class="cfx-reading"><span>價格 · USDT</span><strong>${numPrice(r?.price??d?.price)}</strong></div><dl class="cfx-detail-metrics"><div><dt>${state.heatPeriod.toUpperCase()} 漲跌</dt><dd>${pct(r?.returnPct)}</dd></div><div><dt>本期成交額</dt><dd>${compact(r?.volume)} USDT</dd></div><div><dt>資金費率／${d?.interval||'—'}H</dt><dd>${pct(d?.funding===null?null:d?.funding*100)}</dd></div><div><dt>OI 本位</dt><dd>${compact(d?.baseOI)}</dd></div></dl><div class="cfx-row"><button class="cfx-button" data-jump-derivative="${escape(symbol)}">合約數據 ${icon('arrow')}</button>${market.trades?.[symbol]?.records?.length?`<button class="cfx-button" data-jump-order="${escape(symbol)}">訂單流 ${icon('arrow')}</button>`:''}</div>`;q('.cfx-asset-dialog').showModal();}
 function visibleRotation(){const frame=rotation?.frames[state.frame];return frame?{...frame,rows:frame.rows.filter(r=>(!state.search||r.name.toUpperCase().includes(state.search)||r.members.some(m=>m.base.includes(state.search)))&&(!state.watch||watched.has(r.id)))}:null;}
 function rankMarkup(frame){const rows=[...(frame?.rows||[])].filter(r=>!state.filter||r.state.id===state.filter).sort((a,b)=>state.sort==='share'?(b.shareChange??-Infinity)-(a.shareChange??-Infinity):state.sort==='momentum'?b.y-a.y:b.x-a.x);return `<div class="cfx-side-head"><span>板塊排名</span><select aria-label="板塊排名方式" data-control="sort"><option value="relative" ${state.sort==='relative'?'selected':''}>相對 BTC</option><option value="momentum" ${state.sort==='momentum'?'selected':''}>動能變化</option><option value="share" ${state.sort==='share'?'selected':''}>成交占比變化</option></select></div><div class="cfx-rank-head"><span>板塊</span><span>相對 BTC</span><span>${state.sort==='share'?'占比變化':'動能變化'}</span></div>${rows.map((r,i)=>`<button class="cfx-rank-row" data-sector="${r.id}"><span><i style="background:${r.state.color}"></i>${r.name}<small>${r.state.name} · ${r.members.length}/${r.expectedMembers} 幣</small></span><span class="${color(r.x)}">${pp(r.x)}</span><span class="${color(state.sort==='share'?r.shareChange:r.y)}">${pp(state.sort==='share'?r.shareChange:r.y)}</span></button>`).join('')}${!rows.length?empty('沒有符合篩選的板塊'):''}`;}
 function sectorMarkup(row){const trail=rotation.frames.slice(Math.max(0,state.frame-5),state.frame+1).map(f=>({ts:f.ts,row:f.rows.find(r=>r.id===row.id)})).filter(t=>t.row);return `<div class="cfx-side-head"><span>${row.name}</span><div class="cfx-row"><button class="cfx-watch" data-watch="${row.id}" aria-label="${watched.has(row.id)?'取消':'加入'} ${row.name} 自選" aria-pressed="${watched.has(row.id)}">${watched.has(row.id)?'★':'☆'}</button><button class="cfx-close" data-action="close-sector" aria-label="關閉板塊詳情">${icon('close')}</button></div></div><div class="cfx-selected-state" style="color:${row.state.color}">${row.state.name}<span>${row.members.length} / ${row.expectedMembers} 個成分幣</span></div><dl class="cfx-detail-metrics"><div><dt>相對 BTC</dt><dd>${pp(row.x)}</dd></div><div><dt>動能變化</dt><dd>${pp(row.y)}</dd></div><div><dt>成交占比</dt><dd>${row.share?.toFixed(1)||'—'}% <small>${pp(row.shareChange)}</small></dd></div><div><dt>領先 BTC</dt><dd>${row.members.filter(m=>m.relative>0).length} / ${row.members.length} 幣</dd></div></dl><div class="cfx-trail-history">${trail.map(t=>`<button data-frame-time="${t.ts}" title="${dateLabel(t.ts)} ${t.row.state.name}"><i style="background:${t.row.state.color}"></i><span>${time(t.ts)}</span><small>${t.row.state.name}</small></button>`).join('')}</div><div class="cfx-member-title"><span>成分幣</span><span>${state.period.toUpperCase()} · 依相對強弱</span></div><table class="cfx-table compact"><thead><tr><th>幣種</th><th>漲跌</th><th>相對 BTC</th><th>成交額</th></tr></thead><tbody>${[...row.members].sort((a,b)=>b.relative-a.relative).map(m=>`<tr><td><button data-asset="${m.symbol}">${m.base}</button></td><td class="${color(m.returnPct)}">${pct(m.returnPct)}</td><td>${pp(m.relative)}</td><td>${compact(m.volume)}</td></tr>`).join('')}</tbody></table><div class="cfx-data-note">等權觀察池 · 本期 ${compact(row.turnover)} USDT</div>`;}
 function paintRotation(){const frame=visibleRotation();if(!frame)return;const row=frame.rows.find(r=>r.id===state.selected);const ext=rotation.frames.flatMap(f=>f.rows);const domain={x:Math.max(.1,...ext.map(r=>Math.abs(r.x)))*1.12,y:Math.max(.1,...ext.map(r=>Math.abs(r.y)))*1.12};const trailRows=state.trails?frame.rows:frame.rows.filter(r=>r.id===state.selected);const trails=trailRows.map(r=>({symbol:r.id,color:r.state.color,points:rotation.frames.slice(Math.max(0,state.frame-5),state.frame+1).flatMap(f=>{const p=f.rows.find(x=>x.id===r.id);return p?[{x:p.x,y:p.y}]:[]})}));
  plot?.update(frame.rows,{selected:state.selected,filter:state.filter,rotation:true,equalSize:state.equal,domain,trails,axisX:'相對 BTC 報酬（pp）',axisY:'相對表現變化（pp）',quadrants:['落後改善','領先擴大','落後擴大','領先降溫']});
  q('.cfx-sidebar').innerHTML=row?sectorMarkup(row):rankMarkup(frame);q('.cfx-sidebar').classList.toggle('selected',!!row);
  q('[data-slot="rotation-time"]').textContent=dateLabel(frame.ts)+' UTC+8';q('[data-control="frame"]').value=String(state.frame);
  qa('[data-state]').forEach(b=>{const def=ROTATION_STATES.find(s=>s.id===b.dataset.state);b.innerHTML=`<i style="background:${def.color}"></i>${def.name}<strong>${frame.rows.filter(r=>r.state.id===def.id).length}</strong>`;b.setAttribute('aria-pressed',String(state.filter===def.id));});
  q('[data-slot="rotation-coverage"]').textContent=`${frame.rows.length} 板塊 · ${frame.rows.reduce((s,r)=>s+r.members.length,0)} 幣 · 基準 BTC ${pct(frame.benchmark)}`;
  if(state.table)q('.cfx-rotation-table').innerHTML=`<table class="cfx-table"><thead><tr><th>板塊</th><th>狀態</th><th>漲跌</th><th>相對 BTC</th><th>動能變化</th><th>成交占比</th></tr></thead><tbody>${frame.rows.filter(r=>!state.filter||r.state.id===state.filter).map(r=>`<tr><td><button data-sector="${r.id}">${r.name}</button></td><td style="color:${r.state.color}">${r.state.name}</td><td>${pct(r.returnPct)}</td><td>${pp(r.x)}</td><td>${pp(r.y)}</td><td>${r.share?.toFixed(1)}%</td></tr>`).join('')}</tbody></table>`;
  status('Bitget 快照 · CoinGecko 分類 · 目前觀察池回看',frame.ts);
 }
 function renderRotation(){rotation=buildRotation(market,state.period);state.frame=Math.min(state.frame,rotation.frames.length-1);if(state.frame<0){q('.cfx-content').innerHTML=empty('缺少相鄰期別的完整資料');return;}
  q('.cfx-content').innerHTML=`<div class="cfx-toolbar">${periodButtons(state.period)}<div class="cfx-controls"><button data-action="watch-only" aria-pressed="${state.watch}">自選</button><button data-action="toggle-table" aria-pressed="${state.table}">${state.table?'泡泡':'列表'}</button>${search()}</div></div><div class="cfx-states">${ROTATION_STATES.map(s=>`<button data-state="${s.id}" aria-pressed="false"></button>`).join('')}</div><div class="cfx-layout"><div class="cfx-chart-column"><div class="cfx-chart-meta"><span data-slot="rotation-coverage"></span><div class="cfx-controls"><button data-action="trails" aria-pressed="${state.trails}">軌跡</button><button data-action="equal-size" aria-pressed="${state.equal}">${state.equal?'大小：等大':'大小：成交額'}</button></div></div><div class="cfx-plot" ${state.table?'hidden':''}><canvas role="img" aria-label="加密板塊相對 BTC 輪動圖"></canvas><div class="cfx-zoom"><button data-action="zoom-out" aria-label="縮小">${icon('minus')}</button><button data-action="reset" aria-label="重設圖表">重設</button><button data-action="zoom-in" aria-label="放大">${icon('plus')}</button></div></div><div class="cfx-rotation-table" ${state.table?'':'hidden'}></div><div class="cfx-replay"><button class="cfx-icon" data-action="play" aria-label="播放輪動回放" ${rotation.frames.length<2?'disabled':''}>${icon('play')}</button><input type="range" aria-label="輪動歷史期別" data-control="frame" min="0" max="${rotation.frames.length-1}" step="1" value="${state.frame}"><time data-slot="rotation-time"></time><button data-action="latest">最新</button></div></div><aside class="cfx-sidebar" aria-label="板塊分析"></aside></div>`;
  plot=createFlowChart(q('canvas'),{signal:life.signal,onSelect:id=>{state.selected=id;paintRotation();}});plot.setInteractive(state.focus);paintRotation();
 }
 function renderHeatmap(){const rows=heatmapRows(market,state.heatPeriod).filter(r=>(!state.sector||r.sectorId===state.sector)&&(!state.search||r.base.includes(state.search)));q('.cfx-content').innerHTML=`<div class="cfx-toolbar">${periodButtons(state.heatPeriod,true)}<div class="cfx-controls"><select aria-label="熱力圖面積" data-control="weight"><option value="volume" ${state.weight==='volume'?'selected':''}>本期成交額</option><option value="cap" ${state.weight==='cap'?'selected':''}>市值</option><option value="equal" ${state.weight==='equal'?'selected':''}>等大</option></select><button data-action="group" aria-pressed="${state.grouped}">依板塊</button>${search()}</div></div><div class="cfx-sector-filters"><button data-heat-sector="" aria-pressed="${!state.sector}">全部</button>${market.sectors.map(s=>`<button data-heat-sector="${s.id}" aria-pressed="${state.sector===s.id}">${s.name}</button>`).join('')}</div><div class="cfx-chart-meta"><span>${rows.length} 幣 · ${state.heatPeriod.toUpperCase()} 漲跌</span><span>負值 ← 顏色 → 正值</span></div><div class="cfx-heatmap"><canvas role="img" aria-label="加密市場熱力圖，面積依選定權重，顏色依漲跌幅"></canvas></div><div class="cfx-heat-list">${rows.map(r=>`<button data-asset="${r.symbol}"><b>${r.base}</b><span class="${color(r.returnPct)}">${pct(r.returnPct)}</span></button>`).join('')}</div>`;otherPlot=createToolChart(q('canvas'),{signal:life.signal,onSelect:openAsset});otherPlot.update({type:'heatmap',rows,weight:state.weight,grouped:state.grouped});status(`Bitget 行情快照${state.weight==='cap'?' · 市值：CoinGecko 各幣時間見說明':''} · 觀察池`,rows[0]?.end);}
 function renderFlow(){const model=buildFlow(pressureSnapshot(),state.period==='24h'?'1h':state.period),rows=model.rows.filter(r=>!state.search||r.base.includes(state.search));q('.cfx-content').innerHTML=`<div class="cfx-toolbar">${periodButtons(state.period)}<div class="cfx-controls">${search()}<button data-action="refresh-flow">更新</button></div></div><div class="cfx-chart-meta"><span>${model.rows.length}/${model.expected} 幣 · 面積＝24H 成交額</span><span>主動買賣占比，不是資金淨流入</span></div><div class="cfx-flow-layout"><div class="cfx-plot"><canvas role="img" aria-label="Crypto 主動買賣泡泡圖"></canvas></div><div class="cfx-flow-data"><table class="cfx-table"><thead><tr><th>幣種</th><th>占比</th><th>變化</th><th>狀態</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button data-flow-detail="${r.symbol}">${r.base}</button></td><td>${pct(r.x)}</td><td>${pp(r.y)}</td><td style="color:${r.state.color}">${r.state.name}</td></tr>`).join('')}</tbody></table></div></div>`;plot=createFlowChart(q('canvas'),{signal:life.signal,onSelect:showFlowDetail});plot.update(rows);plot.setInteractive(state.focus);status(`Bitget ${pressureSnapshot().kind==='recorded'?'真實快照':'手動取得'} · ${model.excluded.length} 幣資料未齊`,model.target);}
 function showFlowDetail(symbol){const r=buildFlow(pressureSnapshot(),state.period).rows.find(r=>r.symbol===symbol);if(!r)return;q('[data-slot="asset-title"]').textContent=r.base;q('[data-slot="asset"]').innerHTML=`<span style="color:${r.state.color}">${r.state.name}</span><dl class="cfx-detail-metrics"><div><dt>主動買賣占比</dt><dd>${pct(r.x)}</dd></div><div><dt>占比變化</dt><dd>${pp(r.y)}</dd></div><div><dt>主動買量 · ${r.base}</dt><dd>${compact(r.buy)}</dd></div><div><dt>主動賣量 · ${r.base}</dt><dd>${compact(r.sell)}</dd></div></dl><div class="cfx-balance"><i style="width:${(r.x+100)/2}%"></i></div>`;q('.cfx-asset-dialog').showModal();}
 function renderDerivatives(){const rows=derivativeRows(market).filter(r=>!state.search||r.base.includes(state.search));q('.cfx-content').innerHTML=`<div class="cfx-toolbar"><div class="cfx-controls"><button data-derivative-mode="summary" aria-pressed="${state.derivativeMode!=='oi'}">OI／Funding／Premium</button><button data-derivative-mode="oi" aria-pressed="${state.derivativeMode==='oi'}">OI × Price</button></div>${search()}</div>${state.derivativeMode==='oi'?`<div class="cfx-chart-meta"><span>前次快照 → 本次快照 · OI 以幣本位計算</span><span>不推論多／空開倉方向</span></div><div class="cfx-table-scroll"><table class="cfx-table"><thead><tr><th>幣種</th><th>價格變化</th><th>OI 變化</th><th>觀察</th><th>比較起點</th></tr></thead><tbody>${rows.filter(r=>r.oiChange!==null).map(r=>`<tr><td><button data-asset="${r.symbol}">${r.base}</button></td><td>${pct(r.priceChange)}</td><td>${pct(r.oiChange)}</td><td>${r.priceChange>=0?'價格上升':'價格下降'}／${r.oiChange>=0?'持倉增加':'持倉減少'}</td><td>${dateLabel(r.previousTime)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="cfx-table-scroll"><table class="cfx-table"><thead><tr><th>幣種</th><th>OI · USDT 面值</th><th>資金費率／期</th><th>間隔</th><th>永續溢價</th><th>多空人數比</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button data-asset="${r.symbol}">${r.base}</button></td><td>${compact(r.notional)}</td><td class="${color(r.funding)}">${r.funding===null?'—':pct(r.funding*100)}</td><td>${r.interval||'—'}H</td><td>${pct(r.premium)}</td><td>${r.ratio===null?'—':r.ratio.toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`}`;status('Bitget 快照 · 溢價＝Mark / Index − 1 · 未知欄位保留空白',market.requestTime);}
 function renderOrder(){const stepDefault=state.symbol==='BTCUSDT'?10:state.symbol==='ETHUSDT'?1:.01;const entry=market.trades?.[state.symbol],flow=orderFlow(entry,{step:state.step||stepDefault});const base=state.symbol.replace('USDT','');const decimals=String(state.step).split('.')[1]?.length||0;q('.cfx-content').innerHTML=`<div class="cfx-toolbar"><div class="cfx-controls"><select aria-label="訂單流幣種" data-control="order-symbol">${['BTCUSDT','ETHUSDT','SOLUSDT'].map(s=>`<option ${s===state.symbol?'selected':''}>${s}</option>`).join('')}</select><div class="cfx-period">${[['footprint','Footprint'],['cvd','CVD'],['profile','Volume Profile']].map(([id,n])=>`<button data-order-mode="${id}" aria-pressed="${id===state.orderMode}">${n}</button>`).join('')}</div></div><div class="cfx-controls">${state.orderMode!=='cvd'?`<label>價差 <select data-control="price-step" aria-label="價格分桶">${[stepDefault/2,stepDefault,stepDefault*2,stepDefault*5].map(n=>`<option value="${n}" ${n===state.step?'selected':''}>${n}</option>`).join('')}</select></label>`:''}${state.orderMode==='footprint'?`<select data-control="bar-count" aria-label="可見 K 線數">${[3,6,9].map(n=>`<option value="${n}" ${n===state.count?'selected':''}>${n} 根 · 1m</option>`).join('')}</select>`:''}</div></div><div class="cfx-chart-meta"><span>${flow.trades.length.toLocaleString()} 筆真實成交 · ${time(flow.from)}–${time(flow.to)}</span><span>${state.orderMode==='footprint'?'* 首尾 K 線不完整 · POC 白線':state.orderMode==='cvd'?'自首筆已載入成交歸零':'已載入成交的價量分布'}</span></div>${flow.trades.length?`<div class="cfx-terminal-plot"><canvas role="img" aria-label="${state.orderMode} 真實逐筆成交分析"></canvas></div><div class="cfx-terminal-stats"><span>Buy <b>${compact(flow.buy)}</b></span><span>Sell <b>${compact(flow.sell)}</b></span><span>Delta <b class="${color(flow.delta)}">${signed(flow.delta,3)}</b></span><span>單位 ${base}</span></div>`:empty('尚無可驗證的逐筆成交資料')}`;if(flow.trades.length){otherPlot=createToolChart(q('canvas'),{signal:life.signal,onSelect:barTime=>{const b=flow.bars.find(b=>b.time===barTime);if(!b)return;q('[data-slot="asset-title"]').textContent=`${base} ${time(barTime)} ${b.partial?'（不完整）':''}`;q('[data-slot="asset"]').innerHTML=`<table class="cfx-table"><thead><tr><th>價格</th><th>Bid</th><th>Ask</th><th>Delta</th></tr></thead><tbody>${b.levels.map(l=>`<tr><td>${l.price.toFixed(decimals)}</td><td>${Number(l.bid.toPrecision(4))}</td><td>${Number(l.ask.toPrecision(4))}</td><td>${signed(l.delta,4)}</td></tr>`).join('')}</tbody></table>`;q('.cfx-asset-dialog').showModal();}});otherPlot.update({type:state.orderMode,flow,base,step:state.step,count:state.count,decimals});}status('Bitget REST 成交紀錄 · 限已載入時段 · 未宣稱完整歷史',flow.to);}
 function renderOverview(){const h=heatmapRows(market,'24h'),rot=buildRotation(market,'1h').frames.at(-1),der=derivativeRows(market);q('.cfx-content').innerHTML=`<div class="cfx-overview"><div class="cfx-overview-strip"><span>觀察池上漲 <b>${h.filter(r=>r.returnPct>0).length}/${h.length}</b></span><span>1H 領先 BTC <b>${rot?.rows.filter(r=>r.x>0).length||0}/${rot?.rows.length||0} 板塊</b></span><span>成交額 <b>${compact(h.reduce((s,r)=>s+r.volume,0))} USDT</b></span></div><div class="cfx-overview-columns"><section><div class="cfx-side-head"><span>板塊相對強弱 · 1H</span><button data-tab="rotation">展開 ${icon('arrow')}</button></div>${(rot?.rows||[]).sort((a,b)=>b.x-a.x).map(r=>`<button class="cfx-overview-row" data-overview-sector="${r.id}"><span>${r.name}</span><span style="color:${r.state.color}">${r.state.name}</span><b>${pp(r.x)}</b></button>`).join('')}</section><section><div class="cfx-side-head"><span>主要合約</span><button data-tab="derivatives">展開 ${icon('arrow')}</button></div>${der.filter(r=>['BTC','ETH','SOL'].includes(r.base)).map(r=>`<button class="cfx-overview-row" data-asset="${r.symbol}"><span>${r.base}</span><span>OI ${compact(r.notional)}</span><b>${pct(r.funding*100)} / ${r.interval}H</b></button>`).join('')}<div class="cfx-side-head"><span>24H 強弱</span><button data-tab="heatmap">熱力圖 ${icon('arrow')}</button></div>${[...h].sort((a,b)=>b.returnPct-a.returnPct).slice(0,3).map(r=>`<button class="cfx-overview-row" data-asset="${r.symbol}"><span>${r.base}</span><span>${r.sector}</span><b>${pct(r.returnPct)}</b></button>`).join('')}</section></div></div>`;status('觀察池摘要 · Bitget 真實快照',market.requestTime);}
 function liquidationStats(){const end=liq?.endedAt||Date.now(),begin=Math.max(end-state.liqPeriod*3600000,liq?.connectedAt||end),events=(liq?.events||[]).filter(e=>e.ts>=begin&&e.ts<=end&&(state.liqSymbol==='all'||e.symbol===state.liqSymbol));return {begin,end,events,long:events.filter(e=>e.side==='long').reduce((s,e)=>s+e.amount,0),short:events.filter(e=>e.side==='short').reduce((s,e)=>s+e.amount,0),ready:!!(liq?.acknowledged&&liq?.connectedAt)};}
 function renderLiquidations(){const s=liquidationStats(),total=s.long+s.short;q('.cfx-content').innerHTML=`<div class="cfx-toolbar"><div class="cfx-period">${[1,4,12,24].map(h=>`<button data-liq-period="${h}" aria-pressed="${state.liqPeriod===h}">${h}H</button>`).join('')}</div><div class="cfx-controls"><select data-control="liq-symbol" aria-label="爆倉幣種">${[['all','BTC＋ETH＋SOL'],['BTCUSDT','BTC'],['ETHUSDT','ETH'],['SOLUSDT','SOL']].map(([v,n])=>`<option value="${v}" ${state.liqSymbol===v?'selected':''}>${n}</option>`).join('')}</select><button data-action="connect-liquidations" ${ws?'disabled':''}>${ws?(liq?.acknowledged?'已連線':'連線中…'):'連接 Bybit'}</button></div></div><div class="cfx-liq-stats"><div><span>已觀察總額</span><strong>${s.ready?compact(total):'—'}</strong></div><div><span>多單清算</span><strong>${s.ready?compact(s.long):'—'}</strong></div><div><span>空單清算</span><strong>${s.ready?compact(s.short):'—'}</strong></div></div><div class="cfx-liquidation-balance"><div><span>多單 ${s.ready&&total>0?(100*s.long/total).toFixed(1)+'%':'—'}</span><span>空單 ${s.ready&&total>0?(100*s.short/total).toFixed(1)+'%':'—'}</span></div><div class="cfx-balance ${s.ready&&total>0?'':'unavailable'}"><i style="width:${s.ready&&total>0?100*s.long/total:0}%"></i></div></div><div class="cfx-data-note">${s.ready?`觀察期 ${dateLabel(s.begin)}–${dateLabel(s.end)} · ${Math.round((s.end-s.begin)/60000)} 分鐘；不是完整 ${state.liqPeriod}H 統計。`:'尚未建立可驗證的資料連線，無法提供歷史爆倉總額。'} 單位：USDT 破產價面值。</div><div class="cfx-table-scroll"><table class="cfx-table"><thead><tr><th>時間</th><th>幣種</th><th>清算側</th><th>數量</th><th>破產價面值</th></tr></thead><tbody>${s.events.slice(-100).reverse().map(e=>`<tr><td>${time(e.ts)}</td><td>${escape(e.symbol.replace('USDT',''))}</td><td>${e.side==='long'?'多單':'空單'}</td><td>${compact(e.size)}</td><td>${compact(e.amount)}</td></tr>`).join('')}</tbody></table>${!s.events.length?empty(s.ready?'本觀察期未收到清算事件':'尚無已驗證事件'):''}</div>`;q('.cfx-source-badge').textContent='BYBIT · USDT 永續';status(`Bybit allLiquidation · ${s.ready?'局部觀察':'未連線'} · ${(liq?.gaps||[]).length} 次中斷`,s.ready?s.end:null);}
 function connectLiquidations(){if(ws)return;liq={source:'Bybit',kind:'session',connectedAt:null,startedAt:Date.now(),endedAt:null,acknowledged:false,events:[],gaps:[]};const seen=new Set();ws=new WebSocket('wss://stream.bybit.com/v5/public/linear');const connection=ws;connection.addEventListener('open',()=>{liq.connectedAt=Date.now();connection.send(JSON.stringify({op:'subscribe',args:['BTCUSDT','ETHUSDT','SOLUSDT'].map(s=>'allLiquidation.'+s)}));});connection.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.op==='subscribe'){liq.acknowledged=!!m.success;if(state.tab==='liquidations')renderLiquidations();}if(!m.topic?.startsWith('allLiquidation.'))return;for(const d of m.data||[]){const key=[d.T,d.s,d.S,d.v,d.p].join(':');if(seen.has(key)||!['Buy','Sell'].includes(d.S))continue;const size=Number(d.v),p=Number(d.p);if(!(size>0&&p>0))continue;seen.add(key);liq.events.push({ts:Number(d.T),symbol:d.s,side:d.S==='Buy'?'long':'short',size,amount:size*p});}if(state.tab==='liquidations')renderLiquidations();}catch{}});connection.addEventListener('error',()=>{notice('Bybit 連線未成功；不將資料缺失顯示為零。');});connection.addEventListener('close',()=>{liq.endedAt=Date.now();liq.gaps.push({time:Date.now()});if(ws===connection)ws=null;clearInterval(ping);if(!life.signal.aborted&&state.tab==='liquidations')renderLiquidations();});ping=setInterval(()=>{if(connection.readyState===WebSocket.OPEN)connection.send(JSON.stringify({op:'ping'}));},20000);renderLiquidations();}
 function renderZones(){q('.cfx-content').innerHTML=`<div class="cfx-data-gate"><span class="cfx-gate-symbol">${icon('info')}</span><h2>清算熱區資料尚未接入</h2><p>預估清算分布需要有來源與模型定義的資料。現有公開 K 線、OI 與成交紀錄，無法還原各帳戶的槓桿與清算價。</p><div class="cfx-gate-status"><span>已發生清算事件</span><button data-tab="liquidations">查看爆倉 ${icon('arrow')}</button></div><div class="cfx-gate-status"><span>預估清算密度</span><span>待接授權資料</span></div></div>`;status('未接模型來源 · 未繪製估算熱區');}
 function render(){cleanup();notice('');q('.cfx-source-badge').textContent='BITGET · USDT 永續';qa('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===state.tab)));q('.cfx').classList.toggle('terminal',state.tab==='order');q('.cfx').classList.toggle('focused',state.focus);q('[data-slot="exit-label"]').textContent=state.focus?'退出全螢幕':'全螢幕';if(!market||!flowSnapshot){q('.cfx-content').innerHTML=empty('讀取真實資料…');return;}switch(state.tab){case'rotation':renderRotation();break;case'heatmap':renderHeatmap();break;case'flow':renderFlow();break;case'derivatives':renderDerivatives();break;case'order':renderOrder();break;case'liquidations':renderLiquidations();break;case'zones':renderZones();break;default:renderOverview();}}
 function help(){q('[data-slot="help"]').innerHTML=`<details open><summary>板塊輪動如何閱讀</summary><p>橫軸＝成分幣等權平均報酬 − BTC 同期報酬，單位 pp。縱軸＝本期相對報酬 − 上一期相對報酬。右上為領先擴大、右下為領先降溫、左上為落後改善、左下為落後擴大。</p><p>軌跡連接同一板塊的真實歷史期別；回放使用目前固定觀察池，不代表當時全市場的可投資範圍。每個板塊至少兩個成分幣，且回放所需 K 線完整才納入。</p><p>成交占比＝板塊本期成交額／所有納入板塊本期成交額。占比上升只代表本觀察池的交易活躍度提高，不證明資金從另一板塊轉入。泡泡面積依本期成交額；可切等大。</p></details><details><summary>板塊分類與涵蓋範圍</summary>${market?.sectors.map(s=>`<p><b>${s.name}</b>：${s.members.map(m=>escape(m.replace('USDT',''))).join('、')}<br><a href="${escape(s.source)}" target="_blank" rel="noopener">CoinGecko ${escape(s.categoryId)}</a></p>`).join('')||''}<p>各幣使用明確 CoinGecko ID 與 Bitget 合約符號對應。這是 OX 分類觀察池，不是全板塊完整指數；一個幣只列入一個主要板塊。資料來源缺失的分類不補資料。</p></details><details><summary>主動買賣、熱力圖與合約</summary><p>主動買賣占比＝100 ×（主動買量−主動賣量）／（主動買量＋主動賣量），均為同幣本位單位。縱軸為占比變化，並非資金淨流入。</p><p>熱力圖顏色為 Bitget 同期價格漲跌；面積為本期成交額、CoinGecko 市值或等大。市值各幣時間如下：</p><p>${Object.entries(market?.coins||{}).map(([s,c])=>`${escape(s.replace('USDT',''))} ${dateLabel(Date.parse(c.last_updated))}`).join(' · ')}</p><p>OI USDT 面值＝幣本位持倉 × Mark；OI 變化使用幣本位排除價格放大效應。Funding 顯示各合約本身的收費間隔；永續 Premium 是 Mark 相對 Index 的價差，不是假定到期年化 Basis。多空人數比不代表資金比例。</p></details><details><summary>Footprint／CVD／Volume Profile</summary><p>使用 Bitget fills-history 的真實逐筆成交，依 tradeId 去重。Ask＝主動買、Bid＝主動賣；Delta＝Ask−Bid。價格依設定分桶，時間為 1 分鐘。首尾 K 線標為不完整。完整性僅限取得的 REST 頁面，不宣稱交易所全量歷史。</p><p>CVD 自已載入首筆交易歸零。Volume Profile 加總同價位已載入成交。POC 為最大量價位。斜向不平衡條件：Ask(k) ≥ 3 × Bid(k−1) 或 Bid(k) ≥ 3 × Ask(k＋1)，並達到該根 1% 成交量；分母為零不計比率。門檻只是標記規則，不是買賣訊號。</p></details><details><summary>爆倉與清算熱區</summary><p>Bybit Buy 表示多單遭清算、Sell 表示空單。金額以事件提供的破產價 × 數量呈現，未當作實際成交金額。僅計已連線觀察期間，不用短時間觀察冒充 24H 歷史或全市場。</p><p>Estimated Liquidation Density 尚無授權模型資料，因此不畫預估熱區。它也不等於交易所真實掛單。</p></details>`;q('.cfx-dialog').showModal();}
 async function refreshPressure(){if(request)return;const period=state.period;request=new AbortController();notice('依序取得 Bitget 主動成交資料…');try{const next=await refreshFlow(period,{signal:request.signal,onProgress:(n,total)=>notice(`更新 ${n}/${total} 個標的…`)});if(!buildFlow(next,period).rows.length)throw new Error('沒有可用共同期別');pressureSnapshots.set(period,next);if(state.tab==='flow'&&state.period===period)render();}catch(e){if(e.name!=='AbortError')notice('更新失敗，保留原資料。');}finally{request=null;}}
 function changeTab(tab){state.tab=tab;state.search='';state.selected='';state.filter='';if(tab==='flow'&&state.period==='24h')state.period='1h';render();}
 shadow.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
  if(d.tab){changeTab(d.tab);return;}if(d.period){if(state.tab==='heatmap')state.heatPeriod=d.period;else state.period=d.period;state.frame=7;state.selected='';render();return;}
  if(d.state){state.filter=state.filter===d.state?'':d.state;paintRotation();return;}if(d.sector){state.selected=d.sector;paintRotation();return;}
  if(d.asset){openAsset(d.asset);return;}if(d.flowDetail){showFlowDetail(d.flowDetail);return;}
  if(d.heatSector!==undefined){state.sector=d.heatSector;render();return;}
  if(d.watch){watched.has(d.watch)?watched.delete(d.watch):watched.add(d.watch);try{localStorage.setItem('ox-crypto-sector-watch',JSON.stringify([...watched]));}catch{}paintRotation();return;}
  if(d.frameTime){stopReplay();state.frame=rotation.frames.findIndex(f=>f.ts===Number(d.frameTime));paintRotation();return;}
  if(d.orderMode){state.orderMode=d.orderMode;render();return;}
  if(d.derivativeMode){state.derivativeMode=d.derivativeMode;render();return;}
  if(d.liqPeriod){state.liqPeriod=Number(d.liqPeriod);renderLiquidations();return;}
  if(d.overviewSector){state.tab='rotation';state.period='1h';state.selected=d.overviewSector;state.frame=7;render();return;}
  if(d.jumpOrder){q('.cfx-asset-dialog').close();state.symbol=d.jumpOrder;state.step=state.symbol==='BTCUSDT'?10:state.symbol==='ETHUSDT'?1:.01;changeTab('order');return;}
  if(d.jumpDerivative){q('.cfx-asset-dialog').close();state.tab='derivatives';state.search=d.jumpDerivative.replace('USDT','');render();return;}
  switch(d.action){case'exit':onExit();break;case'help':help();break;case'close-help':q('.cfx-dialog').close();break;case'close-asset':q('.cfx-asset-dialog').close();break;case'close-sector':state.selected='';paintRotation();break;case'fullscreen':state.focus=!state.focus;q('.cfx').classList.toggle('focused',state.focus);q('[data-slot="exit-label"]').textContent=state.focus?'退出全螢幕':'全螢幕';plot?.setInteractive(state.focus);break;
   case'watch-only':state.watch=!state.watch;render();break;case'toggle-table':state.table=!state.table;render();break;case'trails':state.trails=!state.trails;b.setAttribute('aria-pressed',state.trails);paintRotation();break;case'equal-size':state.equal=!state.equal;b.setAttribute('aria-pressed',state.equal);b.textContent=state.equal?'大小：等大':'大小：成交額';paintRotation();break;case'group':state.grouped=!state.grouped;render();break;case'zoom-in':plot?.zoom(.5);break;case'zoom-out':plot?.zoom(-.5);break;case'reset':plot?.reset();break;case'latest':stopReplay();state.frame=rotation.frames.length-1;paintRotation();break;
   case'play':if(replay){stopReplay();break;}if(state.frame===rotation.frames.length-1)state.frame=0;b.innerHTML=icon('pause');b.setAttribute('aria-label','暫停輪動回放');paintRotation();replay=setInterval(()=>{if(state.frame>=rotation.frames.length-1){stopReplay();return;}state.frame++;paintRotation();},1300);break;case'refresh-flow':refreshPressure();break;case'connect-liquidations':connectLiquidations();break;}
 },{signal:life.signal});
 shadow.addEventListener('input',e=>{if(e.target.matches('.cfx-search input')){state.search=e.target.value.trim().toUpperCase();if(state.tab==='rotation')paintRotation();else{const pos=e.target.selectionStart;render();const input=q('.cfx-search input');input?.focus();input?.setSelectionRange(pos,pos);}}if(e.target.dataset.control==='frame'){stopReplay();state.frame=Number(e.target.value);paintRotation();}},{signal:life.signal});
 shadow.addEventListener('change',e=>{switch(e.target.dataset.control){case'sort':state.sort=e.target.value;paintRotation();return;case'weight':state.weight=e.target.value;break;case'order-symbol':state.symbol=e.target.value;state.step=state.symbol==='BTCUSDT'?10:state.symbol==='ETHUSDT'?1:.01;break;case'price-step':state.step=Number(e.target.value);break;case'bar-count':state.count=Number(e.target.value);break;case'liq-symbol':state.liqSymbol=e.target.value;renderLiquidations();return;default:return;}render();},{signal:life.signal});
 function closeInner(){if(q('.cfx-dialog').open){q('.cfx-dialog').close();return true;}if(q('.cfx-asset-dialog').open){q('.cfx-asset-dialog').close();return true;}if(state.selected){state.selected='';if(state.tab==='rotation')paintRotation();return true;}if(state.focus){state.focus=false;q('.cfx').classList.remove('focused');q('[data-slot="exit-label"]').textContent='全螢幕';plot?.setInteractive(false);return true;}return false;}
 shadow.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!closeInner())onExit();}},{signal:life.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopReplay();request?.abort();if(ws){ws.close();ws=null;}clearInterval(ping);}},{signal:life.signal});
 render();if(!market||!flowSnapshot){(async()=>{try{const fetchJSON=async u=>{const r=await fetch(u,{signal:life.signal});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();};const values=await Promise.all([market?Promise.resolve(market):fetchJSON(marketURL),flowSnapshot?Promise.resolve(flowSnapshot):fetchJSON(snapshotURL),liq?Promise.resolve(liq):fetchJSON(liquidationURL).catch(()=>null)]);[market,flowSnapshot,liq]=values;if(!life.signal.aborted)render();}catch(e){if(e.name!=='AbortError')notice('資料載入失敗，請重新開啟預覽。');}})();}
 return {closeInner,destroy(){life.abort();request?.abort();cleanup();q('.cfx-dialog')?.close();q('.cfx-asset-dialog')?.close();shadow.innerHTML='';}};
}
