import { buildFlow, STATES, signed, compact, dateLabel } from './flow-model.js';
import { buildRotation, heatmapRows, ROTATION_STATES, TOOL_PERIODS } from './tools-model.js?v=20261001-loading1';
import { createFlowChart } from './flow-chart.js?v=20261001-loading1';
import { createToolChart } from './tools-charts.js?v=20261005-graytop5';
import { refreshFlow } from './flow-source.js';
import { revealStyledShadow } from '../../../components/style-ready.js?v=20261005-load16';
import { refreshMarket } from './market-live.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={close:'<path d="m6 6 12 12M18 6 6 18"/>',back:'<path d="m10 5-7 7 7 7M3 12h18"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',reset:'<path d="M3 4v6h6M4 10a8 8 0 1 1 1 8"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 4v16M16 4v16"/>',settings:'<path d="M4 7h16M4 17h16M8 4v6M16 14v6"/>',refresh:'<path d="M4 4v6h6M4 10a8 8 0 1 1 1 8"/>',plus:'<path d="M5 12h14M12 5v14"/>',minus:'<path d="M5 12h14"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`;
const snapshotURL=new URL('../../../../previews/data/crypto-flow-snapshot.json',import.meta.url);
const marketURL=new URL('../../../../previews/data/crypto-tools-snapshot.json',import.meta.url);
const cssURL=new URL('./flow.css?v=20261005-tools12',import.meta.url);
const numPrice=v=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:v<1?6:2}):'—';
const pct=v=>Number.isFinite(v)?signed(v,2)+'%':'—';
const pp=v=>Number.isFinite(v)?signed(v,2)+'pp':'—';
const color=v=>v>=0?'positive':'negative';
const time=t=>new Date(t).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false});
const TABS=[['heatmap','熱力圖'],['rotation','板塊輪動'],['flow','主動買賣']];
let cachedMarket=null,cachedFlow=null;
function loadCached(url,kind){
 const current=kind==='market'?cachedMarket:cachedFlow;
 if(current)return current;
 const next=fetch(url,{signal:AbortSignal.timeout(12000)}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).catch(e=>{if(kind==='market')cachedMarket=null;else cachedFlow=null;throw e;});
 if(kind==='market')cachedMarket=next;else cachedFlow=next;
 return next;
}
export function mountCryptoFlow(host,{onExit=()=>{},snapshot=null,marketSnapshot=null,initialTab='rotation',autoRefresh=false}={}) {
 const shadow=host.shadowRoot||host.attachShadow({mode:'open'}),life=new AbortController();
 const state={tab:TABS.some(([id])=>id===initialTab)?initialTab:'rotation',period:'1h',heatPeriod:'24h',selected:'',filter:'',sector:'',search:'',frame:7,equal:true,trails:false,table:false,weight:matchMedia('(max-width:600px)').matches?'equal':'volume',grouped:false,focus:false,symbol:'BTCUSDT',sort:'relative',watch:false};
 let market=marketSnapshot,flowSnapshot=snapshot,rotation=null,plot=null,otherPlot=null,replay=null,request=null,marketRequest=null,lastMarketAttempt=0,lastPressureAttempt=0,marketTimer=null;
 const pressureSnapshots=new Map();
 async function refreshCurrentMarket(){if(!autoRefresh||!market||marketRequest||document.hidden)return;
  if(Date.now()-Number(market.requestTime)<5*60000)return;
  marketRequest=new AbortController();lastMarketAttempt=Date.now();notice('正在更新 Bitget 觀察池…');
  const loading=window.OXLoading?.begin('crypto','更新熱力圖與板塊',{signal:marketRequest.signal,total:market.tickers.length,done:0,views:['strength'],target:q('[data-slot="loading"]')});
  try{const next=await refreshMarket(market,{signal:marketRequest.signal,onProgress:(n,total)=>{loading?.update(n,total);if(n===total||n%5===0)notice(`Bitget 更新 ${n}/${total} 幣…`);}});
   if(!life.signal.aborted){market=next;cachedMarket=Promise.resolve(next);render();}
  }catch(e){if(e.name!=='AbortError'&&!life.signal.aborted)notice(`即時更新失敗：${e.message}；目前顯示有時間戳的快照。`);}
  finally{marketRequest=null;loading?.finish();}
 }
 const maybeRefreshMarket=()=>{if(!autoRefresh||document.hidden)return;if(['heatmap','rotation'].includes(state.tab)&&Date.now()-lastMarketAttempt>5*60000)void refreshCurrentMarket();if(state.tab==='flow'&&Date.now()-lastPressureAttempt>5*60000&&Date.now()-Date.parse(pressureSnapshot()?.captureCompletedAt||pressureSnapshot()?.capturedAt)>5*60000)void refreshPressure();};
 const pressureSnapshot=()=>pressureSnapshots.get(state.period)||flowSnapshot;
 const watched=new Set();try{for(const s of JSON.parse(localStorage.getItem('ox-crypto-sector-watch')||'[]'))watched.add(s);}catch{}
 shadow.innerHTML=`<link rel="stylesheet" href="${cssURL.href}"><main class="cfx"><header class="cfx-top"><button class="cfx-icon cfx-back" data-action="exit" aria-label="返回指標">${icon('back')}</button><span class="cfx-brand">OX<span>CRYPTO</span></span><span class="cfx-source-badge">BITGET · USDT 永續</span><div class="cfx-top-actions"><button class="cfx-icon" data-action="help" aria-label="資料與計算說明">${icon('info')}</button><button class="cfx-exit" data-action="fullscreen">${icon('expand')}<span data-slot="exit-label">全螢幕</span></button></div></header><nav class="cfx-tabs" aria-label="Crypto 工具">${TABS.map(([id,label])=>`<button data-tab="${id}" aria-pressed="${id===state.tab}">${label}</button>`).join('')}</nav><section class="cfx-content" aria-label="工具內容"></section><footer class="cfx-status" role="status"><span data-slot="loading" hidden></span><span data-slot="source">讀取來源資料…</span><span data-slot="period"></span></footer><div class="cfx-notice" role="status" hidden></div><dialog class="cfx-dialog" aria-label="資料與計算說明"><div class="cfx-dialog-head"><span>資料與計算</span><button class="cfx-close" data-action="close-help" aria-label="關閉說明">${icon('close')}</button></div><div data-slot="help"></div></dialog><dialog class="cfx-settings-dialog cfx-dialog" aria-label="圖表設定"><div class="cfx-dialog-head"><span>圖表設定</span><button class="cfx-close" data-action="close-settings" aria-label="關閉圖表設定">${icon('close')}</button></div><div data-slot="settings"></div></dialog><dialog class="cfx-asset-dialog" aria-label="標的詳情"><div class="cfx-dialog-head"><span data-slot="asset-title"></span><button class="cfx-close" data-action="close-asset" aria-label="關閉標的詳情">${icon('close')}</button></div><div data-slot="asset"></div></dialog></main>`;
 revealStyledShadow(shadow,life.signal);
 const q=s=>shadow.querySelector(s),qa=s=>[...shadow.querySelectorAll(s)];
 const notice=text=>{q('.cfx-notice').textContent=text;q('.cfx-notice').hidden=!text;};
 function cleanup(){request?.abort();plot?.destroy();otherPlot?.destroy();plot=otherPlot=null;stopReplay();}
 function stopReplay(){clearInterval(replay);replay=null;const b=q('[data-action="play"]');if(b){b.innerHTML=icon('play');b.setAttribute('aria-label','播放輪動回放');}}
 function toolbar(period, heat = false, refresh = false) {
  return `<div class="cfx-toolbar cfx-toolbar-compact"><select class="cfx-period-select" data-control="period" aria-label="時間級別">${Object.keys(TOOL_PERIODS).filter(t=>heat||t!=='24h').map(t=>`<option value="${t}" ${period===t?'selected':''}>${t.toUpperCase()}</option>`).join('')}</select>${search()}<button class="cfx-icon" data-action="settings" aria-label="圖表設定" title="圖表設定">${icon('settings')}</button><button class="cfx-icon" data-action="fullscreen" aria-label="全螢幕" title="全螢幕">${icon('expand')}</button>${refresh?`<button class="cfx-icon" data-action="refresh-flow" aria-label="更新資料" title="更新資料">${icon('refresh')}</button>`:''}</div>`;
 }
 function renderSettings() {
  const body=q('[data-slot="settings"]');
  const toggle=(action,text,pressed)=>`<button data-action="${action}" aria-pressed="${pressed}">${text}</button>`;
  let options='';
  if(state.tab==='rotation')options=toggle('watch-only','只看自選',state.watch)+toggle('toggle-table','顯示列表',state.table)+toggle('trails','顯示軌跡',state.trails)+toggle('equal-size','泡泡等大',state.equal);
  if(state.tab==='heatmap')options=`<label>面積<select data-control="weight" aria-label="熱力圖面積">${[['volume','本期成交額'],['cap','市值'],['equal','等大']].map(([id,text])=>`<option value="${id}" ${state.weight===id?'selected':''}>${text}</option>`).join('')}</select></label>${toggle('group','依板塊排列',state.grouped)}<label>板塊<select data-control="heat-sector" aria-label="熱力圖板塊"><option value="">全部</option>${(market?.sectors||[]).map(row=>`<option value="${row.id}" ${state.sector===row.id?'selected':''}>${row.name}</option>`).join('')}</select></label>`;
  body.innerHTML=`<div class="cfx-settings-options cfx-controls">${options}<button data-action="help">資料與計算說明</button></div>`;
 }

 const search=()=>`<label class="cfx-search">${icon('search')}<input aria-label="搜尋板塊或幣種" placeholder="搜尋" value="${escape(state.search)}"></label>`;
 const empty=text=>`<div class="cfx-empty">${text}</div>`;
 function status(text,stamp){q('[data-slot="source"]').textContent=text;q('[data-slot="period"]').textContent=stamp?dateLabel(stamp)+' UTC+8':'';}
 function openAsset(symbol){const r=heatmapRows(market,state.heatPeriod).find(x=>x.symbol===symbol);q('[data-slot="asset-title"]').textContent=symbol.replace(/USDT$/,'');q('[data-slot="asset"]').innerHTML=`<div class="cfx-reading"><span>價格 · USDT</span><strong>${numPrice(r?.price)}</strong></div><dl class="cfx-detail-metrics"><div><dt>${state.heatPeriod.toUpperCase()} 漲跌</dt><dd>${pct(r?.returnPct)}</dd></div><div><dt>本期成交額</dt><dd>${compact(r?.volume)} USDT</dd></div></dl>`;q('.cfx-asset-dialog').showModal();}
 function visibleRotation(){const frame=rotation?.frames[state.frame];return frame?{...frame,rows:frame.rows.filter(r=>(!state.search||r.name.toUpperCase().includes(state.search)||r.members.some(m=>m.base.includes(state.search)))&&(!state.watch||watched.has(r.id)))}:null;}
 function rankMarkup(frame){const rows=[...(frame?.rows||[])].filter(r=>!state.filter||r.state.id===state.filter).sort((a,b)=>state.sort==='share'?(b.shareChange??-Infinity)-(a.shareChange??-Infinity):state.sort==='momentum'?b.y-a.y:b.x-a.x);return `<div class="cfx-side-head"><span>板塊排名</span><select aria-label="板塊排名方式" data-control="sort"><option value="relative" ${state.sort==='relative'?'selected':''}>相對 BTC</option><option value="momentum" ${state.sort==='momentum'?'selected':''}>動能變化</option><option value="share" ${state.sort==='share'?'selected':''}>成交占比變化</option></select></div><div class="cfx-rank-head"><span>板塊</span><span>相對 BTC</span><span>${state.sort==='share'?'占比變化':'動能變化'}</span></div>${rows.map((r,i)=>`<button class="cfx-rank-row" data-sector="${r.id}"><span><i style="background:${r.state.color}"></i>${r.name}<small>${r.state.name} · ${r.members.length}/${r.expectedMembers} 幣</small></span><span class="${color(r.x)}">${pp(r.x)}</span><span class="${color(state.sort==='share'?r.shareChange:r.y)}">${pp(state.sort==='share'?r.shareChange:r.y)}</span></button>`).join('')}${!rows.length?empty('沒有符合篩選的板塊'):''}`;}
 function sectorMarkup(row){const trail=rotation.frames.slice(Math.max(0,state.frame-5),state.frame+1).map(f=>({ts:f.ts,row:f.rows.find(r=>r.id===row.id)})).filter(t=>t.row);return `<div class="cfx-side-head"><span>${row.name}</span><div class="cfx-row"><button class="cfx-watch" data-watch="${row.id}" aria-label="${watched.has(row.id)?'取消':'加入'} ${row.name} 自選" aria-pressed="${watched.has(row.id)}">${watched.has(row.id)?'★':'☆'}</button><button class="cfx-close" data-action="close-sector" aria-label="關閉板塊詳情">${icon('close')}</button></div></div><div class="cfx-selected-state" style="color:${row.state.color}">${row.state.name}<span>${row.members.length} / ${row.expectedMembers} 個成分幣</span></div><dl class="cfx-detail-metrics"><div><dt>相對 BTC</dt><dd>${pp(row.x)}</dd></div><div><dt>動能變化</dt><dd>${pp(row.y)}</dd></div><div><dt>成交占比</dt><dd>${row.share?.toFixed(1)||'—'}% <small>${pp(row.shareChange)}</small></dd></div><div><dt>領先 BTC</dt><dd>${row.members.filter(m=>m.relative>0).length} / ${row.members.length} 幣</dd></div></dl><div class="cfx-trail-history">${trail.map(t=>`<button data-frame-time="${t.ts}" title="${dateLabel(t.ts)} ${t.row.state.name}"><i style="background:${t.row.state.color}"></i><span>${time(t.ts)}</span><small>${t.row.state.name}</small></button>`).join('')}</div><div class="cfx-member-title"><span>成分幣</span><span>${state.period.toUpperCase()} · 依相對強弱</span></div><table class="cfx-table compact"><thead><tr><th>幣種</th><th>漲跌</th><th>相對 BTC</th><th>成交額</th></tr></thead><tbody>${[...row.members].sort((a,b)=>b.relative-a.relative).map(m=>`<tr><td><button data-asset="${m.symbol}">${m.base}</button></td><td class="${color(m.returnPct)}">${pct(m.returnPct)}</td><td>${pp(m.relative)}</td><td>${compact(m.volume)}</td></tr>`).join('')}</tbody></table><div class="cfx-data-note">等權觀察池 · 本期 ${compact(row.turnover)} USDT</div>`;}
 function paintRotation(){const frame=visibleRotation();if(!frame)return;const row=frame.rows.find(r=>r.id===state.selected);const ext=rotation.frames.flatMap(f=>f.rows);const domain={x:Math.max(.1,...ext.map(r=>Math.abs(r.x)))*1.12,y:Math.max(.1,...ext.map(r=>Math.abs(r.y)))*1.12};const trailRows=state.trails?frame.rows:frame.rows.filter(r=>r.id===state.selected);const trails=trailRows.map(r=>({symbol:r.id,color:r.state.color,points:rotation.frames.slice(Math.max(0,state.frame-5),state.frame+1).flatMap(f=>{const p=f.rows.find(x=>x.id===r.id);return p?[{x:p.x,y:p.y}]:[]})}));
  plot?.update(frame.rows,{selected:state.selected,filter:state.filter,rotation:true,equalSize:state.equal,domain,trails,axisX:'相對 BTC 報酬（pp）',axisY:'相對表現變化（pp）',quadrants:['落後改善','領先擴大','落後擴大','領先降溫']});
  q('.cfx-sidebar').innerHTML=row?sectorMarkup(row):rankMarkup(frame);q('.cfx-sidebar').classList.toggle('selected',!!row);
  q('[data-slot="rotation-time"]').textContent=dateLabel(frame.ts)+' UTC+8';q('[data-control="frame"]').value=String(state.frame);
  qa('[data-state]').forEach(b=>{const def=ROTATION_STATES.find(s=>s.id===b.dataset.state);b.innerHTML=`<i style="background:${def.color}"></i>${def.name}<strong>${frame.rows.filter(r=>r.state.id===def.id).length}</strong>`;b.setAttribute('aria-pressed',String(state.filter===def.id));});
  q('[data-slot="rotation-coverage"]').textContent=`${frame.rows.length} 板塊 · ${frame.rows.reduce((s,r)=>s+r.members.length,0)} 幣 · 基準 BTC ${pct(frame.benchmark)}`;
  if(state.table)q('.cfx-rotation-table').innerHTML=`<table class="cfx-table"><thead><tr><th>板塊</th><th>狀態</th><th>漲跌</th><th>相對 BTC</th><th>動能變化</th><th>成交占比</th></tr></thead><tbody>${frame.rows.filter(r=>!state.filter||r.state.id===state.filter).map(r=>`<tr><td><button data-sector="${r.id}">${r.name}</button></td><td style="color:${r.state.color}">${r.state.name}</td><td>${pct(r.returnPct)}</td><td>${pp(r.x)}</td><td>${pp(r.y)}</td><td>${r.share?.toFixed(1)}%</td></tr>`).join('')}</tbody></table>`;
  status(`Bitget ${market.kind==='foreground-refresh'?'更新':'快照'} · CoinGecko 分類 · 目前觀察池回看`,frame.ts);
 }
 function renderRotation(){rotation=buildRotation(market,state.period);state.frame=Math.min(state.frame,rotation.frames.length-1);if(state.frame<0){q('.cfx-content').innerHTML=empty('缺少相鄰期別的完整資料');return;}
  q('.cfx-content').innerHTML=`${toolbar(state.period)}<div class="cfx-states">${ROTATION_STATES.map(s=>`<button data-state="${s.id}" aria-pressed="false"></button>`).join('')}</div><div class="cfx-layout"><div class="cfx-chart-column"><div class="cfx-chart-meta"><span data-slot="rotation-coverage"></span></div><div class="cfx-plot" ${state.table?'hidden':''}><canvas role="img" aria-label="加密板塊相對 BTC 輪動圖，可雙指縮放與拖曳"></canvas><div class="cfx-zoom"><button data-action="zoom-out" aria-label="縮小">${icon('minus')}</button><button data-action="reset" aria-label="重設圖表">${icon('reset')}</button><button data-action="zoom-in" aria-label="放大">${icon('plus')}</button></div></div><div class="cfx-rotation-table" ${state.table?'':'hidden'}></div><div class="cfx-replay"><button class="cfx-icon" data-action="play" aria-label="播放輪動回放" ${rotation.frames.length<2?'disabled':''}>${icon('play')}</button><input type="range" aria-label="輪動歷史期別" data-control="frame" min="0" max="${rotation.frames.length-1}" step="1" value="${state.frame}"><time data-slot="rotation-time"></time><button data-action="latest">最新</button></div></div><aside class="cfx-sidebar" aria-label="板塊分析"></aside></div>`;
  plot=createFlowChart(q('canvas'),{signal:life.signal,onSelect:id=>{state.selected=id;paintRotation();}});plot.setInteractive(true);paintRotation();
 }
 function renderHeatmap(){const rows=heatmapRows(market,state.heatPeriod).filter(r=>(!state.sector||r.sectorId===state.sector)&&(!state.search||r.base.includes(state.search)));q('.cfx-content').innerHTML=`${toolbar(state.heatPeriod,true)}<div class="cfx-chart-meta"><span>${rows.length} 幣 · ${state.heatPeriod.toUpperCase()} · ${state.weight==='equal'?'等大':state.weight==='cap'?'市值面積':'成交額面積'}</span><span>負值 ← 顏色 → 正值</span></div><div class="cfx-heatmap"><canvas role="img" aria-label="加密市場熱力圖，可雙指縮放、滑鼠滾輪縮放與拖曳，面積依選定權重，顏色依漲跌幅"></canvas><div class="cfx-zoom"><button data-action="heat-out" aria-label="縮小熱力圖">−</button><button data-action="heat-reset" aria-label="重設熱力圖">${icon('reset')}</button><button data-action="heat-in" aria-label="放大熱力圖">＋</button></div></div><div class="cfx-heat-list">${rows.map(r=>`<button data-asset="${r.symbol}"><b>${r.base}</b><span class="${color(r.returnPct)}">${pct(r.returnPct)}</span></button>`).join('')}</div>`;otherPlot=createToolChart(q('canvas'),{signal:life.signal,onSelect:openAsset});otherPlot.update({type:'heatmap',rows,weight:state.weight,grouped:state.grouped});status(`Bitget 行情${market.kind==='foreground-refresh'?'更新':'快照'}${state.weight==='cap'?' · 市值：CoinGecko 各幣時間見說明':''} · 觀察池`,rows[0]?.end);}
 function renderFlow(){const model=buildFlow(pressureSnapshot(),state.period==='24h'?'1h':state.period),rows=model.rows.filter(r=>!state.search||r.base.includes(state.search));q('.cfx-content').innerHTML=`${toolbar(state.period,false,true)}<div class="cfx-chart-meta"><span>${model.rows.length}/${model.expected} 幣 · 面積＝24H 成交額</span><span>主動買賣占比，不是資金淨流入</span></div><div class="cfx-flow-layout"><div class="cfx-plot"><canvas role="img" aria-label="Crypto 主動買賣泡泡圖，可雙指縮放與拖曳"></canvas><div class="cfx-zoom"><button data-action="zoom-out" aria-label="縮小">${icon('minus')}</button><button data-action="reset" aria-label="重設圖表">${icon('reset')}</button><button data-action="zoom-in" aria-label="放大">${icon('plus')}</button></div></div><div class="cfx-flow-data"><table class="cfx-table"><thead><tr><th>幣種</th><th>占比</th><th>變化</th><th>狀態</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button data-flow-detail="${r.symbol}">${r.base}</button></td><td>${pct(r.x)}</td><td>${pp(r.y)}</td><td style="color:${r.state.color}">${r.state.name}</td></tr>`).join('')}</tbody></table></div></div>`;plot=createFlowChart(q('canvas'),{signal:life.signal,onSelect:showFlowDetail});plot.update(rows);plot.setInteractive(true);status(`Bitget ${pressureSnapshot().kind==='recorded'?'真實快照':'手動取得'} · ${model.excluded.length} 幣資料未齊`,model.target);}
 function showFlowDetail(symbol){const r=buildFlow(pressureSnapshot(),state.period).rows.find(r=>r.symbol===symbol);if(!r)return;q('[data-slot="asset-title"]').textContent=r.base;q('[data-slot="asset"]').innerHTML=`<span style="color:${r.state.color}">${r.state.name}</span><dl class="cfx-detail-metrics"><div><dt>主動買賣占比</dt><dd>${pct(r.x)}</dd></div><div><dt>占比變化</dt><dd>${pp(r.y)}</dd></div><div><dt>主動買量 · ${r.base}</dt><dd>${compact(r.buy)}</dd></div><div><dt>主動賣量 · ${r.base}</dt><dd>${compact(r.sell)}</dd></div></dl><div class="cfx-balance"><i style="width:${(r.x+100)/2}%"></i></div>`;q('.cfx-asset-dialog').showModal();}
 function render(){renderSettings();cleanup();notice('');q('.cfx-source-badge').textContent='BITGET · USDT 永續';qa('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===state.tab)));q('.cfx').classList.toggle('focused',state.focus);q('[data-slot="exit-label"]').textContent=state.focus?'退出全螢幕':'全螢幕';if(!market||!flowSnapshot){q('.cfx-content').innerHTML=empty(window.OXLoading?.markup('讀取市場資料')||'讀取市場資料…');return;}switch(state.tab){case'rotation':renderRotation();break;case'heatmap':renderHeatmap();break;case'flow':renderFlow();break;default:renderRotation();}maybeRefreshMarket();}
 function help(){q('[data-slot="help"]').innerHTML=`<details open><summary>板塊輪動如何閱讀</summary><p>橫軸＝成分幣等權平均報酬 − BTC 同期報酬，單位 pp。縱軸＝本期相對報酬 − 上一期相對報酬。右上為領先擴大、右下為領先降溫、左上為落後改善、左下為落後擴大。</p><p>軌跡連接同一板塊的真實歷史期別；回放使用目前固定觀察池，不代表當時全市場的可投資範圍。每個板塊至少兩個成分幣，且回放所需 K 線完整才納入。</p><p>成交占比＝板塊本期成交額／所有納入板塊本期成交額。占比上升只代表本觀察池的交易活躍度提高，不證明資金從另一板塊轉入。泡泡面積依本期成交額；可切等大。</p></details><details><summary>板塊分類與涵蓋範圍</summary>${market?.sectors.map(s=>`<p><b>${s.name}</b>：${s.members.map(m=>escape(m.replace('USDT',''))).join('、')}<br><a href="${escape(s.source)}" target="_blank" rel="noopener">CoinGecko ${escape(s.categoryId)}</a></p>`).join('')||''}<p>各幣使用明確 CoinGecko ID 與 Bitget 合約符號對應。這是 OX 分類觀察池，不是全板塊完整指數；一個幣只列入一個主要板塊。資料來源缺失的分類不補資料。</p></details><details><summary>Footprint／CVD／Volume Profile</summary><p>使用 Bitget fills-history 的真實逐筆成交，依 tradeId 去重。Ask＝主動買、Bid＝主動賣；Delta＝Ask−Bid。價格依設定分桶，時間為 1 分鐘。首尾 K 線標為不完整。完整性僅限取得的 REST 頁面，不宣稱交易所全量歷史。</p><p>CVD 自已載入首筆交易歸零。Volume Profile 加總同價位已載入成交。POC 為最大量價位。斜向不平衡條件：Ask(k) ≥ 3 × Bid(k−1) 或 Bid(k) ≥ 3 × Ask(k＋1)，並達到該根 1% 成交量；分母為零不計比率。門檻只是標記規則，不是買賣訊號。</p></details>`;q('.cfx-dialog').showModal();}
 async function refreshPressure(){if(request)return;lastPressureAttempt=Date.now();const period=state.period;request=new AbortController();const loading=window.OXLoading?.begin('crypto','更新主動成交標的',{signal:request.signal,views:['strength'],target:q('[data-slot="loading"]')});notice('依序取得 Bitget 主動成交資料…');try{const next=await refreshFlow(period,{signal:request.signal,onProgress:(n,total)=>{loading?.update(n,total);notice(`更新 ${n}/${total} 個標的…`);}});if(!buildFlow(next,period).rows.length)throw new Error('沒有可用共同期別');pressureSnapshots.set(period,next);if(state.tab==='flow'&&state.period===period)render();}catch(e){if(e.name!=='AbortError')notice('更新失敗，保留原資料。');}finally{request=null;loading?.finish();}}
 function changeTab(tab){state.tab=tab;state.search='';state.selected='';state.filter='';if(tab==='flow'&&state.period==='24h')state.period='1h';render();}
 shadow.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
  if(d.tab){changeTab(d.tab);return;}if(d.period){if(state.tab==='heatmap')state.heatPeriod=d.period;else state.period=d.period;state.frame=7;state.selected='';render();return;}
  if(d.state){state.filter=state.filter===d.state?'':d.state;paintRotation();return;}if(d.sector){state.selected=d.sector;paintRotation();return;}
  if(d.asset){openAsset(d.asset);return;}if(d.flowDetail){showFlowDetail(d.flowDetail);return;}
  if(d.heatSector!==undefined){state.sector=d.heatSector;render();return;}
  if(d.watch){watched.has(d.watch)?watched.delete(d.watch):watched.add(d.watch);try{localStorage.setItem('ox-crypto-sector-watch',JSON.stringify([...watched]));}catch{}paintRotation();return;}
  if(d.frameTime){stopReplay();state.frame=rotation.frames.findIndex(f=>f.ts===Number(d.frameTime));paintRotation();return;}
  switch(d.action){case'retry-data':void loadData();break;case'settings':renderSettings();q('.cfx-settings-dialog').showModal();break;case'close-settings':q('.cfx-settings-dialog').close();break;case'exit':onExit();break;case'help':q('.cfx-settings-dialog').close();help();break;case'close-help':q('.cfx-dialog').close();break;case'close-asset':q('.cfx-asset-dialog').close();break;case'close-sector':state.selected='';paintRotation();break;case'fullscreen':state.focus=!state.focus;q('.cfx').classList.toggle('focused',state.focus);q('[data-slot="exit-label"]').textContent=state.focus?'退出全螢幕':'全螢幕';plot?.setInteractive(state.focus);break;
   case'watch-only':state.watch=!state.watch;render();break;case'toggle-table':state.table=!state.table;render();break;case'trails':state.trails=!state.trails;b.setAttribute('aria-pressed',state.trails);paintRotation();break;case'equal-size':state.equal=!state.equal;b.setAttribute('aria-pressed',state.equal);paintRotation();break;case'group':state.grouped=!state.grouped;render();break;case'heat-in':otherPlot?.zoom(1.3);break;case'heat-out':otherPlot?.zoom(1/1.3);break;case'heat-reset':otherPlot?.reset();break;case'zoom-in':plot?.zoom(.5);break;case'zoom-out':plot?.zoom(-.5);break;case'reset':plot?.reset();break;case'latest':stopReplay();state.frame=rotation.frames.length-1;paintRotation();break;
   case'play':if(replay){stopReplay();break;}if(state.frame===rotation.frames.length-1)state.frame=0;b.innerHTML=icon('pause');b.setAttribute('aria-label','暫停輪動回放');paintRotation();replay=setInterval(()=>{if(state.frame>=rotation.frames.length-1){stopReplay();return;}state.frame++;paintRotation();},1300);break;case'refresh-flow':refreshPressure();break;}
 },{signal:life.signal});
 shadow.addEventListener('input',e=>{if(e.target.matches('.cfx-search input')){state.search=e.target.value.trim().toUpperCase();if(state.tab==='rotation')paintRotation();else{const pos=e.target.selectionStart;render();const input=q('.cfx-search input');input?.focus();input?.setSelectionRange(pos,pos);}}if(e.target.dataset.control==='frame'){stopReplay();state.frame=Number(e.target.value);paintRotation();}},{signal:life.signal});
 shadow.addEventListener('change',e=>{switch(e.target.dataset.control){case'period':if(state.tab==='heatmap')state.heatPeriod=e.target.value;else state.period=e.target.value;state.frame=7;state.selected='';break;case'heat-sector':state.sector=e.target.value;break;case'sort':state.sort=e.target.value;paintRotation();return;case'weight':state.weight=e.target.value;break;default:return;}render();},{signal:life.signal});
 function closeInner(){if(q('.cfx-settings-dialog').open){q('.cfx-settings-dialog').close();return true;}if(q('.cfx-dialog').open){q('.cfx-dialog').close();return true;}if(q('.cfx-asset-dialog').open){q('.cfx-asset-dialog').close();return true;}if(state.selected){state.selected='';if(state.tab==='rotation')paintRotation();return true;}if(state.focus){state.focus=false;q('.cfx').classList.remove('focused');q('[data-slot="exit-label"]').textContent='全螢幕';plot?.setInteractive(false);return true;}return false;}
 shadow.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!closeInner())onExit();}},{signal:life.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopReplay();request?.abort();}},{signal:life.signal});
 let dataPending=false;
 async function loadData(){if(dataPending||life.signal.aborted)return;dataPending=true;render();try{const values=await Promise.all([market?Promise.resolve(market):loadCached(marketURL,'market'),flowSnapshot?Promise.resolve(flowSnapshot):loadCached(snapshotURL,'flow')]);if(life.signal.aborted)return;[market,flowSnapshot]=values;render();}catch(e){if(!life.signal.aborted){q('.cfx-content').innerHTML=empty('資料暫時無法取得')+'<button class="cfx-button" data-action="retry-data">重試</button>';notice('');}}finally{dataPending=false;}}
 render();if(autoRefresh)marketTimer=setInterval(()=>{if(!life.signal.aborted)maybeRefreshMarket();},60000);if(!market||!flowSnapshot)void loadData();
 return {closeInner,destroy(){life.abort();request?.abort();marketRequest?.abort();clearInterval(marketTimer);cleanup();q('.cfx-settings-dialog')?.close();q('.cfx-dialog')?.close();q('.cfx-asset-dialog')?.close();shadow.innerHTML='';}};
}
