// Server-rendered operator test page. No application scripts or browser storage.
export const COOKIE_PATH = '/api/v1/account/bitget-status';
export const TEST_PATH = COOKIE_PATH + '?view=test';
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

export function renderOperatorPage({ session, message = '', result, uid = '' } = {}) {
  const csrf = session ? `<input type="hidden" name="csrf" value="${escape(session.nonce)}">` : '';
  let output = '';
  if (result) {
    const referral = result.referral.status === 'matched' ? '已找到直客關係' : '未找到直客關係';
    const certification = { passed: '認證已通過（KYC／KYB）', not_passed: '認證未通過', unknown: '目前無法確認', not_checked: '尚未查詢認證' }[result.certification.status] || '目前無法確認';
    const date = result.registration.registeredAt ? new Date(result.registration.registeredAt).toLocaleString('zh-TW', { timeZone: 'Asia/Taipei', hour12: false }) : '未提供';
    output = `<section class="result" aria-labelledby="result-title"><p class="eyebrow">Bitget 實際回覆</p><h2 id="result-title">查詢完成</h2><dl><div><dt>UID</dt><dd>${escape(result.uid)}</dd></div><div><dt>推薦關係</dt><dd>${referral}</dd></div><div><dt>註冊時間（台北）</dt><dd>${escape(date)}</dd></div><div><dt>認證結果</dt><dd>${certification}</dd></div></dl><p class="hint">認證預設查詢最近 90 天。沒有紀錄不等於未通過；未找到直客關係，也不代表帳號不存在。查詢不會綁定帳號或變更會員資格。</p></section>`;
  }
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="color-scheme" content="dark"><title>Bitget 連線測試｜OX</title><link rel="stylesheet" href="/src/styles/account/operator-test.css"></head><body><header><a class="brand" href="/" aria-label="返回 OX 市場">OX<span>OXLOVE</span></a><span class="tag">管理員工具</span></header><main><aside><p class="eyebrow">OX 帳號服務</p><h1>確認連線，<br>掌握每一步。</h1><p>查詢 Bitget 推薦關係與認證結果。</p><div class="light" aria-hidden="true"></div></aside><article class="card"><p class="eyebrow">Bitget 連線測試</p><h2>${session ? '查詢一筆帳號' : '開始安全測試'}</h2><p class="intro">${session ? '輸入你有權查詢的客戶 UID。' : '使用你剛在 Vercel 設定的查詢密碼。'}</p>${message ? `<p class="notice" role="alert">${escape(message)}</p>` : ''}${session ? `<form method="post" action="${TEST_PATH}">${csrf}<input type="hidden" name="action" value="lookup"><label for="uid">Bitget 客戶 UID</label><input id="uid" name="uid" inputmode="numeric" pattern="[1-9][0-9]{0,19}" maxlength="20" required autocomplete="off" value="${escape(uid)}" placeholder="輸入客戶 UID"><p class="hint">請使用你代理名下的客戶 UID；代理本人 UID 不一定能查到直客關係。</p><button type="submit">查詢註冊與認證</button></form>${output}<form class="logout" method="post" action="${TEST_PATH}">${csrf}<input type="hidden" name="action" value="logout"><button class="secondary" type="submit">結束測試並登出</button></form><p class="hint">此測試授權在 10 分鐘後到期。</p>` : `<form method="post" action="${TEST_PATH}"><input type="hidden" name="action" value="login"><label for="password">查詢密碼</label><input id="password" name="password" type="password" required minlength="32" maxlength="512" autocomplete="current-password" aria-describedby="password-help"><p id="password-help" class="hint">填入 OX_ACCOUNT_LOOKUP_TOKEN 的值，至少 32 個字元。不是 Bitget API 金鑰，也不是交易所登入密碼。</p><button type="submit">進入測試</button></form>`}<a class="back" href="/">返回 OX 市場</a></article></main><footer>僅供維運查詢 · 資料由 Bitget 回傳</footer></body></html>`;
}
