const { createServer } = require('node:http');
const { readFileSync, existsSync, mkdirSync, writeFileSync } = require('node:fs');
const { resolve, extname } = require('node:path');
const { chromium, webkit } = require('playwright');
const root = resolve(__dirname, '..'), port = Number(process.env.OX_NEWS_QA_PORT || 4196), base = `http://127.0.0.1:${port}`;
const out = resolve(root, 'docs/qa/news-v2', process.env.OX_NEWS_ENGINE === 'webkit' ? 'webkit' : '.'); mkdirSync(out, { recursive: true });
const snapshot = JSON.parse(readFileSync(resolve(root, 'data/news.json'), 'utf8'));
const server = createServer((req, res) => {
  const path = new URL(req.url, base).pathname;
  const file = resolve(root, '.' + (path === '/' ? '/index.html' : path));
  if (!file.startsWith(root + '/') || !existsSync(file) || path.includes('/.')) { res.writeHead(404); res.end('Not found'); return; }
  try { res.setHeader('Content-Type', ({ '.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.json':'application/json;charset=utf-8','.svg':'image/svg+xml','.png':'image/png' })[extname(file)] || 'application/octet-stream'); res.end(readFileSync(file)); } catch { res.writeHead(404); res.end('Not found'); }
});
function assert(value, message) { if (!value) throw Error(message); }
const report = { engine: process.env.OX_NEWS_ENGINE || 'chromium', screenshots: [], viewports: [], interactions: [], errors: [] };
const pause = ms => new Promise(r => setTimeout(r, ms));
async function contextFor(browser, size, options = {}) {
  const context = await browser.newContext({ viewport: size, isMobile: size.width < 600, hasTouch: size.width < 600, ...options });
  await context.addInitScript(() => { if (window.top !== window) return; try { localStorage.setItem('ox-setting-oxLive','1'); } catch {} });
  const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
  const vendor = process.env.OX_NEWS_VENDOR_FILE;
  if (vendor && existsSync(vendor)) await page.route('https://unpkg.com/**', r => r.fulfill({ contentType:'text/javascript', body:readFileSync(vendor,'utf8') }));
  // Guest configuration is an explicit unconfigured backend in the local static server.
  await page.route('**/api/v1/account/config', r => r.fulfill({ json: { configured:false, providerConnectionVerified:false, databaseConnected:false } }));
  return {context,page,errors};
}
async function load(page, hash = '#news/crypto') { await page.goto(base + '/' + hash, { waitUntil:'domcontentloaded', timeout:35000 }); await page.locator('.oxn-calendar-grid').waitFor({timeout:20000}); await pause(450); }
async function tab(page, name) { await page.locator(`.oxn-tabs [data-news-tab="${name}"]`).click(); }
async function shot(page, name) { await pause(400); await page.screenshot({ path:resolve(out, name) }); report.screenshots.push(name); }
async function bounds(page) {
  return page.evaluate(() => { const grid = document.querySelector('.oxn-calendar-grid'), cal = grid?.closest('.oxn-calendar'), dock = document.querySelector('.app-dock'); return { overflow:document.documentElement.scrollWidth-innerWidth, weeks:Number(cal?.dataset.weeks), calendarBottom:cal?.getBoundingClientRect().bottom, dockTop:dock.getBoundingClientRect().top, gridHeight:grid?.getBoundingClientRect().height, liveVisible:document.querySelector('.ox-live-shell')?.getBoundingClientRect().height > 0 }; });
}
(async () => {
  await new Promise(r => server.listen(port,'127.0.0.1',r));
  const engine = report.engine === 'webkit' ? webkit : chromium;
  const browser = await engine.launch({headless:true,...(process.env.OX_BROWSER_PATH ? {executablePath:process.env.OX_BROWSER_PATH} : {})});
  try {
    for (const size of (process.env.OX_NEWS_ONLY_INTERACTIONS ? [] : [{width:1440,height:900},{width:1366,height:768},{width:390,height:844},{width:375,height:667},{width:430,height:932}])) {
      const {context,page,errors} = await contextFor(browser,size); await load(page);
      let result = await bounds(page); assert(result.overflow <= 1, `${size.width}: horizontal overflow`);
      if (size.width < 600) assert(result.calendarBottom < result.dockTop, `${size.width}: 5-week month extends below dock ${JSON.stringify(result)}`);
      if(size.width===1440 || size.width===390) await shot(page,`${size.width<600?'mobile':'desktop'}-calendar.png`);
      await page.getByRole('button',{name:'選擇年份月份'}).click();await page.locator('.oxn-popover').getByRole('button',{name:'8 月',exact:true}).click();await pause(450);result=await bounds(page);assert(result.weeks===6,'August must have six weeks');if(size.width<600)assert(result.calendarBottom<result.dockTop,`${size.width}: 6-week month extends below dock ${JSON.stringify(result)}`);
      if(size.width===375)await shot(page,'small-mobile-six-weeks.png');
      await tab(page,'key'); assert(await page.locator('.oxn-controls .oxn-pill').count()===4,'four news pills only');assert(await page.locator('.oxn-news-row').count()>0,'real crypto news must render');
      if(size.width===1440 || size.width===390)await shot(page,`${size.width<600?'mobile':'desktop'}-key-news.png`);
      const sourceButton=page.getByRole('button',{name:'多選新聞來源'});await sourceButton.click();const panel=page.locator('.oxn-popover.is-open');await panel.waitFor();
      const panelBounds=await panel.boundingBox();assert(panelBounds.x>=0&&panelBounds.x+panelBounds.width<=size.width,'source panel outside viewport');assert(await panel.locator('input[type="checkbox"]').count()===0,'no checkboxes');
      assert(await panel.getByRole('button',{name:/科技新報/}).count()===0,'crypto must not show Taiwan media');
      const topBefore=await page.locator('.oxn-news-range').boundingBox();await panel.getByRole('button',{name:'清除選取',exact:true}).click();assert(await page.locator('.oxn-news-row').count()===0,'no sources must mean zero articles');assert(await panel.isVisible(),'multi-select must remain open');await panel.getByRole('button',{name:'恢復預設'}).click();assert(await page.locator('.oxn-news-row').count()>0,'restore sources');const topAfter=await page.locator('.oxn-news-range').boundingBox();assert(Math.abs(topBefore.y-topAfter.y)<1,'floating panel must not move the list');
      if(size.width===390)await shot(page,'mobile-multi-select.png');await panel.getByRole('button',{name:'關閉篩選'}).click();await pause(300);assert(await page.locator('.oxn-popover').count()===0,'popover cleanup');
      await page.getByRole('button',{name:'新聞資產提及排行'}).click();assert(await page.locator('.oxn-ranking button').count()>0,'real crypto asset ranking');if(size.width===1440)await shot(page,'desktop-ranking.png');await page.keyboard.press('Escape');await pause(300);
      report.viewports.push({size,...result});report.errors.push(...errors);await context.close();
    }
    const {context,page,errors}=await contextFor(browser,{width:390,height:844});await load(page);
    // History nesting uses real events from the production snapshot, not fixtures.
    const event=snapshot.events.find(e=>e.kind==='token-unlock'&&e.date?.startsWith('2026-10')) || snapshot.events.find(e=>e.markets.includes('crypto')&&e.date?.startsWith('2026-10'));
    const day=event.date || new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(event.occursAt));
    await page.locator(`[data-date="${day}"] .oxn-day-number`).click();await page.locator('.oxn-modal').waitFor();assert((await page.locator('.oxn-modal .oxn-event-row').count())>0,'day events');await page.locator('.oxn-modal .oxn-event-row').first().click();await page.getByRole('dialog',{name:'事件詳情'}).waitFor();await shot(page,'crypto-event-detail.png');
    await page.getByRole('button',{name:'返回上一層'}).click();await page.getByRole('dialog',{name:new RegExp('當日事件')}).waitFor();await page.goForward();await page.getByRole('dialog',{name:'事件詳情'}).waitFor();await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('dialog',{name:'事件詳情'}).waitFor();await pause(500);assert((await page.locator('.oxn-fields').count())===1,'deep event reload');await page.goBack();await page.getByRole('dialog',{name:new RegExp('當日事件')}).waitFor();await page.goBack();await pause(300);assert(await page.locator('.oxn-modal-backdrop').count()===0,'no modal after returning to calendar');
    // News entry single tap, double tap, long press, cancel and scroll compatibility.
    const entry=page.locator('.app-dock [data-view-target="data"]');await entry.tap();await pause(420);assert(await page.locator('#view-data.active').count()===1,'single tap opens market news');
    const entryBox=await entry.boundingBox();await page.touchscreen.tap(entryBox.x+entryBox.width/2,entryBox.y+entryBox.height/2);await pause(70);await page.touchscreen.tap(entryBox.x+entryBox.width/2,entryBox.y+entryBox.height/2);await pause(80);assert(await page.locator('#ox-news-entry-menu.is-open').count()===1,'double tap opens choice menu without navigation');await shot(page,'mobile-news-entry.png');await page.locator('#ox-news-entry-menu [data-destination="all"]').tap();await pause(250);assert(await page.locator('#view-news.active').count()===1,'all news via old menu');
    await page.getByRole('button',{name:'返回先前頁面'}).click();await pause(350);assert(await page.locator('#view-data.active').count()===1,'all news returns to prior market');
    await entry.dispatchEvent('pointerdown',{pointerId:31,pointerType:'touch',isPrimary:true,button:0,clientX:300,clientY:800});await pause(530);assert(await page.locator('#ox-news-entry-menu.is-open').count()===1,'long press opens news menu');await entry.dispatchEvent('pointercancel',{pointerId:31,pointerType:'touch'});await page.locator('.oxn-title').click();await pause(320);
    await entry.dispatchEvent('pointerdown',{pointerId:32,pointerType:'touch',isPrimary:true,button:0,clientX:300,clientY:800});await entry.dispatchEvent('pointermove',{pointerId:32,pointerType:'touch',clientX:300,clientY:760});await pause(530);assert(await page.locator('#ox-news-entry-menu.is-open').count()===0,'movement cancels long hold');await entry.dispatchEvent('pointercancel',{pointerId:32,pointerType:'touch'});
    await page.evaluate(()=>window.OXMarketController.setMarket('tw'));await page.evaluate(()=>window.OXNews.openMarket({market:'tw'}));await page.locator('.oxn-root[data-scope="tw"]').waitFor();await pause(350);assert(await page.locator('.oxn-calendar-grid').count()===1,'Taiwan uses same calendar');
    const twEvent=snapshot.events.find(e=>e.markets.includes('tw')&&e.category==='dividend-preview'&&e.cashDividend!=null&&e.date.startsWith('2026-10'));assert(twEvent,'real TW dividends needed');await page.locator(`[data-date="${twEvent.date}"] .oxn-day-number`).click();await page.locator('.oxn-modal').getByRole('button',{name:twEvent.titleZh,exact:true}).click();await page.getByRole('dialog',{name:'事件詳情'}).waitFor();await shot(page,'tw-event-detail.png');await page.goBack();await pause(120);await page.goBack();await pause(250);
    await tab(page,'key');await page.getByRole('button',{name:'多選新聞來源'}).click();assert(await page.locator('.oxn-popover').getByRole('button',{name:/科技新報/}).count()===1,'TW source catalog');assert(await page.locator('.oxn-popover').getByRole('button',{name:/CoinDesk/}).count()===0,'TW excludes crypto media');await page.keyboard.press('Escape');await pause(300);
    // Each market retains its own tab/month/filters; original all-news host uses the same workspace.
    await page.evaluate(()=>{window.OXMarketController.setMarket('crypto');window.OXNews.openMarket({market:'crypto'});});await page.locator('.oxn-root[data-scope="crypto"] .oxn-calendar-grid').waitFor();
    assert(await page.locator('.oxn-tabs [data-news-tab="calendar"]').getAttribute('aria-selected')==='true','TW tab must not overwrite crypto tab');
    await page.locator('.oxn-calendar-event').first().click();await page.getByRole('dialog',{name:'事件詳情'}).waitFor();await page.goBack();await pause(320);assert(await page.locator('.oxn-modal-backdrop').count()===0,'direct event returns once to calendar');
    await page.evaluate(()=>{window.OXMarketController.setMarket('tw');window.OXNews.openMarket({market:'tw'});});await page.locator('.oxn-root[data-scope="tw"] .oxn-news-list').waitFor();
    assert(await page.locator('.oxn-tabs [data-news-tab="key"]').getAttribute('aria-selected')==='true','TW preserves its own key-news tab');
    await page.getByRole('button',{name:'多選新聞時間'}).click();let multi=page.locator('.oxn-popover.is-open');await multi.getByRole('button',{name:'3 小時',exact:true}).click();assert(await multi.getByRole('button',{name:'3 小時',exact:true}).getAttribute('aria-pressed')==='true','time union 3h selected');assert(await multi.getByRole('button',{name:'24 小時',exact:true}).getAttribute('aria-pressed')==='true','24h remains selected');await multi.getByRole('button',{name:'關閉篩選'}).click();await pause(300);
    await tab(page,'calendar');await page.getByRole('button',{name:'多選事件類別'}).click();multi=page.locator('.oxn-popover.is-open');await multi.getByRole('button',{name:/^除權息預告/}).click();await multi.getByRole('button',{name:/^法說會/}).click();assert(await multi.locator('.oxn-tag[aria-pressed="true"]').count()===2,'event categories multiselect');assert(await multi.getByRole('button',{name:'全部',exact:true}).getAttribute('aria-pressed')==='false','all and specific selection do not conflict');await multi.getByRole('button',{name:'恢復預設'}).click();await page.keyboard.press('Escape');await pause(300);
    await page.getByRole('button',{name:'多選重要性'}).click();multi=page.locator('.oxn-popover.is-open');await multi.getByRole('button',{name:'★★ 中',exact:true}).click();await multi.getByRole('button',{name:'★★★ 高',exact:true}).click();assert(await multi.locator('.oxn-tag[aria-pressed="true"]').count()===2,'importance multiselect');await multi.getByRole('button',{name:'恢復預設'}).click();await page.keyboard.press('Escape');await pause(300);
    await page.evaluate(()=>window.OXNews.open());await page.locator('.oxn-root[data-scope="all"] .oxn-calendar-grid').waitFor();assert(await page.locator('.oxn-tabs [role="tab"]').count()===2,'original news total view has two tabs');await shot(page,'mobile-all-calendar.png');await page.getByRole('button',{name:'返回先前頁面'}).click();await page.locator('.oxn-root[data-scope="tw"]').waitFor();
    await page.evaluate(()=>window.switchAppView('radar'));const radar=page.locator('.app-dock .dock-radar');await radar.dispatchEvent('touchstart',{touches:[{identifier:1,clientX:190,clientY:800}],changedTouches:[{identifier:1,clientX:190,clientY:800}]});await pause(500);await radar.dispatchEvent('touchend',{touches:[],changedTouches:[{identifier:1,clientX:190,clientY:800}]});await pause(100);const menu=page.locator('#ox-market-quick-switch');assert(await menu.locator('[data-market]').count()===2,'two radar markets');const buttons=await menu.locator('[data-market]').evaluateAll(bs=>bs.map(b=>({id:b.dataset.market,width:b.getBoundingClientRect().width})));assert(buttons.map(b=>b.id).join(',')==='crypto,tw','only crypto/tw');assert(Math.abs(buttons[0].width-buttons[1].width)<1,'equal market widths');await shot(page,'mobile-radar-two-markets.png');
    // Unchanged market/home/indicator/account entry points remain usable.
    await page.evaluate(()=>window.OXMarketController.setMarket('us'));await pause(400);await page.evaluate(()=>window.switchAppView('data'));await page.locator('.us2-news-tabs').waitFor();assert(await page.locator('.us2-news-tabs button').count()===2,'US data workspace survives');
    await page.evaluate(()=>window.OXMarketController.setMarket('crypto'));await page.evaluate(()=>window.switchAppView('home'));await page.locator('#view-home.active').waitFor();await page.evaluate(()=>window.switchAppView('strength'));await page.locator('#view-strength.active').waitFor();assert(await page.locator('.app-dock .dock-btn').count()===5,'original five navigation entries retained');assert(await page.locator('#ox-control-open').count()===1,'account/control entry retained');
    report.interactions.push('nested history/back/forward/reload','market state isolation','single/double/long tap and move cancel','two market radar menu','multi-select all/none/reset','real title-based crypto ranking');report.errors.push(...errors);await context.close();
    // Desktop hover stays open while entering the popup; keyboard is also usable.
    const desk=await contextFor(browser,{width:1440,height:900});await load(desk.page);const de=desk.page.locator('.ox-desktop-nav [data-view-target="data"]');await de.hover();await desk.page.locator('#ox-news-entry-menu button').first().hover();await pause(250);assert(await desk.page.locator('#ox-news-entry-menu.is-open').count()===1,'hover must remain open across menu');await shot(desk.page,'desktop-news-entry.png');await desk.page.keyboard.press('Escape');await de.focus();await desk.page.keyboard.press('ArrowUp');assert(await desk.page.locator('#ox-news-entry-menu button').first().evaluate(n=>n===document.activeElement),'keyboard opens menu');report.errors.push(...desk.errors);await desk.context.close();
    // Explicit isolated test modes for pending, failure, empty and late responses.
    const slow=await contextFor(browser,{width:390,height:844});let release;const barrier=new Promise(r=>release=r);await slow.page.route('**/data/news.json*',async r=>{await barrier;await r.fulfill({json:snapshot});});await slow.page.goto(base+'/#news/crypto',{waitUntil:'domcontentloaded'});await pause(350);await slow.page.evaluate(()=>window.OXNews.openMarket({market:'tw'}));release();await slow.page.locator('.oxn-root[data-scope="tw"] .oxn-calendar-grid').waitFor();assert((await slow.page.locator('.oxn-title').innerText()).includes('台股'),'late response must preserve new market');await slow.context.close();
    const empty=await contextFor(browser,{width:390,height:844});await empty.page.route('**/data/news.json*',r=>r.fulfill({json:{schemaVersion:1,generatedAt:snapshot.generatedAt,news:[],events:[],sources:[]}}));await load(empty.page);await tab(empty.page,'key');assert(await empty.page.locator('.oxn-empty').count()>0,'successful empty state');await empty.context.close();
    const fail=await contextFor(browser,{width:390,height:844});await fail.page.route('**/data/news.json*',r=>r.fulfill({status:503,body:'temporary failure'}));await fail.page.goto(base+'/#news',{waitUntil:'domcontentloaded'});await fail.page.getByRole('button',{name:'重試',exact:true}).waitFor();assert((await fail.page.locator('.oxn-content').innerText()).includes('無法讀取'),'failed state with retry');await fail.context.close();
    const partial=await contextFor(browser,{width:390,height:844});const partialData=JSON.parse(JSON.stringify(snapshot));partialData.sources=partialData.sources.map(x=>x.id==='coindesk'?{...x,status:'error',message:'Explicit QA source failure'}:x);await partial.page.route('**/data/news.json*',r=>r.fulfill({json:partialData}));await load(partial.page);await tab(partial.page,'key');assert(await partial.page.locator('.oxn-news-row').count()>0,'source failure must retain articles');await partial.page.getByRole('button',{name:'多選新聞來源'}).click();assert((await partial.page.locator('.oxn-popover').getByRole('button',{name:/CoinDesk/}).innerText()).includes('更新失敗'),'source failure distinct from zero');await partial.page.keyboard.press('Escape');await pause(320);
    await partial.page.locator('.oxn-news-row summary').first().click();await partial.page.evaluate(()=>scrollTo(0,250));const reading=await partial.page.locator('.oxn-news-row[open]').getAttribute('data-news-id');partialData.generatedAt=new Date().toISOString();await partial.page.evaluate(()=>window.OXNews.refresh(true));await partial.page.getByRole('button',{name:'有新消息・點此更新'}).waitFor();assert(await partial.page.locator(`.oxn-news-row[data-news-id="${reading}"]`).getAttribute('open')!==null,'new snapshot preserves expanded reading until accepted');await partial.context.close();
    const accessible=await contextFor(browser,{width:375,height:667},{reducedMotion:'reduce'});await load(accessible.page);await accessible.page.evaluate(()=>document.documentElement.style.fontSize='24px');await accessible.page.setViewportSize({width:667,height:375});await pause(350);assert(await accessible.page.locator('.oxn-calendar-grid').count()===1,'landscape/enlarged text remains scrollable');assert((await bounds(accessible.page)).overflow<=1,'landscape has no horizontal overflow');await accessible.context.close();
    report.interactions.push('slow response ignored for stale market','successful empty','503 retry','source failure retains last articles','new-snapshot notification preserves reading','landscape and reduced motion');
    assert(report.errors.length===0,'runtime errors: '+report.errors.join(' | '));report.passed=true;console.log(JSON.stringify(report,null,2));
  } finally {writeFileSync(resolve(out,`qa-${report.engine}.json`),JSON.stringify(report,null,2)+'\n');await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exit(1)});
